apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-1.5.1
    heritage: Tiller
    release: prom-ops
    team: identity
  name: prom-ops-prometheus-operat-prometheus
  namespace: ops
spec:
  alerting:
    alertmanagers:
    - name: prom-ops-prometheus-operat-alertmanager
      namespace: ops
      pathPrefix: /
      port: web
  baseImage: quay.io/prometheus/prometheus
  externalUrl: http://prom-ops.identity.astro.com.my/
  listenLocal: false
  logLevel: info
  paused: false
  replicas: 1
  retention: 20d
  routePrefix: /
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: prom-ops
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prom-ops-prometheus-operat-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prom-ops
  storage:
    volumeClaimTemplate:
      selector: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: encrypted-1a
  version: v2.6.0
